name: Mirror Repository 

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set-ssh
      run: |
        # SSHディレクトリ作成
        mkdir ~/.ssh
        # 権限を設定
        chmod 700 ~/.ssh
        # secretに保存されているパスフレーズなしの秘密鍵を出力する
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        # 権限を限定する
        chmod 600 ~/.ssh/id_rsa
    - name: clone
      run: |
        # ミラー用ディレクトリ作成
        mkdir ~/mirror
        # ミラー用ディレクトリに移動
        cd ~/mirror
        # ミラー用リポジトリをclone
        git clone git@github.com:miu200521358/ror-sample-mirror.git
        # ファイル存在確認
        ls -l ./   
    - name: export
      run: |
        # リポジトリの最新ソースを zip でexportする
        git archive --format=zip HEAD > ~/original.zip
        # ファイル存在確認
        ls -l ~/original.zip
        # zipを展開する(既存上書き)
        unzip -o -d ~/original ~/original.zip
    - name: copy
      run: |
        # オリジナルをミラーにコピーする
        cp -r ~/original ~/mirror
    - name: diff
      run: |
        # ミラー用リポジトリに移動
        cd ~/mirror
        # 差分表示
        git diff
        
        
#       uses: pixta-dev/repository-mirroring-action@v1
#       with:
#         # SSH private key for ssh connection to the target repository
#         ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
#         # Target url
#         target_repo_url: git@github.com:miu200521358/ror-sample-mirror.git

