name: Mirror Repository 

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # ミラー先リポジトリ名
      MIRROR_REPOSITORY_NAME: ror-sample-mirror
      # ミラー先のリポジトリSSHパス
      MIRROR_RIPOSITORY:  git@github.com:miu200521358/ror-sample-mirror.git
    steps:
    - uses: actions/checkout@v2
    - name: set-ssh
      run: |
        mkdir ~/.ssh                                            # SSHディレクトリ作成
        chmod 700 ~/.ssh                                        # 権限を設定
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa   # secretに保存されているパスフレーズなしの秘密鍵を出力する
        chmod 600 ~/.ssh/id_rsa                                 # 権限を限定する
    - name: clone
      run: |
        mkdir ~/mirror                        # ミラー用ディレクトリ作成
        cd ~/mirror                           # ミラー用ディレクトリに移動
        git clone $MIRROR_RIPOSITORY          # ミラー用リポジトリをclone
        ls -l ./                              # ファイル存在確認
    - name: export
      run: |
        git archive --format=zip HEAD > ~/original.zip        # リポジトリの最新ソースを zip でexportする
        ls -l ~/original.zip                                  # ファイル存在確認
        unzip -o -d ~/original ~/original.zip                 # zipを展開する(既存上書き)
    - name: copy
      run: |
        cp -r ~/original ~/mirror/$MIRROR_REPOSITORY_NAME     # オリジナルをミラーにコピーする
    - name: diff
      run: |
        cd ~/mirror/$MIRROR_REPOSITORY_NAME                 # ミラー用リポジトリに移動
        git diff                                            # 差分表示

        
        
#       uses: pixta-dev/repository-mirroring-action@v1
#       with:
#         # SSH private key for ssh connection to the target repository
#         ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
#         # Target url
#         target_repo_url: git@github.com:miu200521358/ror-sample-mirror.git

