name: CI

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
            echo test, and deploy your project.
    - name: Mirroring Repository
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        # SSH private key for ssh connection to the target repository
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        # Target url
        target_repo_url: https://github.com/miu200521358/ror-sample-mirror
