name: Mirror Repository 

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # ミラー先リポジトリ名
      mirror-repository-name: ror-sample-mirror
      # ミラー先のリポジトリSSHパス
      mirror-ripository:  git@github.com:miu200521358/ror-sample-mirror.git
    steps:
    - uses: actions/checkout@v2
    - name: clone
      run: |
        # ミラー用ディレクトリ作成
        mkdir ~/mirror
        # ミラー用ディレクトリに移動
        cd ~/mirror
        # ミラー用リポジトリをclone
        git clone git@github.com:miu200521358/${{ env.mirror-repository }}.git
        # ファイル存在確認
        ls -l ./   
    - name: export
      run: |
        # リポジトリの最新ソースを zip でexportする
        git archive --format=zip HEAD > ~/original.zip
        # ファイル存在確認
        ls -l ~/original.zip
        # zipを展開する(既存上書き)
        unzip -o -d ~/original ~/original.zip
    - name: copy
      run: |
        # オリジナルをミラーにコピーする
        cp -r ~/original ~/mirror/${{ env.mirror-repository-name }}
    - name: diff
      run: |
        # ミラー用リポジトリに移動
        cd ~/mirror/${{ env.mirror-repository-name }}
        # 差分表示
        git diff
        
        
#       uses: pixta-dev/repository-mirroring-action@v1
#       with:
#         # SSH private key for ssh connection to the target repository
#         ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
#         # Target url
#         target_repo_url: git@github.com:miu200521358/ror-sample-mirror.git

