name: Mirror Repository 

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: test
      run: ls -la /dev/tty
    - name: Mirroring Repository
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        # SSH private key for ssh connection to the target repository
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        # Target url
        target_repo_url: git@github.com:miu200521358/ror-sample-mirror.git
